### ISSUE TITLE
Is it possible to pick only groups, not individual contacts?

### ISSUE THREAD

**Issue by retorquere** [1gravity/Android-ContactPicker#1]

**Comment by 1gravity** [comment]
Picking a group automatically selects the contacts of that group. The individual contacts are then returned to the caller. The question is, what would you do with a group only? At the moment I can't see a use case for this but you might enlighten me?

**Comment by retorquere** [comment]
I'm looking to integrate group-based blocking to Signal messenger. If I
pick a group to block and later add a person to they group, I'd expect that
person to be blocked too without me having me to repick the group in signal
(which would sort of defeat the purpose of picking a group)

**Comment by 1gravity** [comment]
With 07d3114ee8bc9ab6f4425ba72e7a79a9c0b0dc63 the ContactPickerActivity also returns the picked groups. If you need to know the contacts for that groups after the groups has been modified (users deleted/added/modified), you'd have to re-query the contacts. The code to query contacts can be found in the ContactPickerActivity (you might want to query only the group contacts though)..
