### ISSUE TITLE
While settings my own AppTheme I got an exception...

### ISSUE THREAD

**Issue by thatsmoodi** [1gravity/Android-ContactPicker#22]
Attribute undefined. cp_TextColorPrimary Did you apply to correct theme.

I want to set the AppTheme which is my default App theme.

 .putExtra(ContactPickerActivity.EXTRA_THEME, R.style.AppTheme)

I have read that
/**
     * Use this parameter to set the Theme for this activity.
     * It's the theme's resource id (like R.style.YourFancyTheme)..
     * Please note that the theme needs to define the attributes defined in attrs.xml or the
     * Activity will crash. You can either extend the library's theme(s) or define the attributes in
     * your custom theme.
     */

What are other attributes that I need to set.

**Comment by 1gravity** [comment]
all the attributes defined in the attrs.xml file.

**Comment by thatsmoodi** [comment]
I have copied this style theme. It is still giving an error. 


    <style name="Theme_Light_Base" parent="@style/ContactPicker_Theme_Light">
        
        <item name="colorPrimary">@color/colorPrimary_light</item>
        <item name="colorAccent">@color/colorAccent_light</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark_light</item>

        <item name="backgroundColor">@color/background_light</item>
        <item name="icTheme">@drawable/ic_palette_black_36dp</item>
        <item name="icPickContact">@drawable/ic_person_add_black_36dp</item>
    </style>

    <style name="Theme_Light" parent="@style/Theme_Light_Base"/>


error:
Error:(2442, 21) No resource found that matches the given name: attr 'backgroundColor'.
Error:(2444, 21) No resource found that matches the given name: attr 'icPickContact'.
Error:(2443, 21) No resource found that matches the given name: attr 'icTheme'.
Error:(2442, 21) No resource found that matches the given name: attr 'backgroundColor'.
Error:(2444, 21) No resource found that matches the given name: attr 'icPickContact'.
Error:(2443, 21) No resource found that matches the given name: attr 'icTheme'.

**Comment by 1gravity** [comment]
backgroundColor, icPickContact and icTheme are your own custom attributes and have nothing to do with the library. Please consult this: https://developer.android.com/guide/topics/ui/themes.html.

**Comment by 1gravity** [comment]
There was a typo in one the the style definitions, try the new version 1.3.1
