### ISSUE TITLE
Error :- Attribute Undefined : "cp_textColorPrimary". Did you apply correct theme ?

### ISSUE THREAD

**Issue by DhiralKaniya** [1gravity/Android-ContactPicker#25]
I have follow your instruction and i got this toast menu instead of Contact Layout with ContactPickerActivity.

1 :- My Dependencies are
dependencies {

    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.1gravity:android-contactpicker:1.3.1'
    testCompile 'junit:junit:4.12'
}

2 :- My AndroidMenifest.xml file 
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.the_king.findnotification">

    <uses-permission android:name="android.permission.READ_CONTACTS" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.LAUNCHER" />/>
            </intent-filter>
        </activity>
        <activity
            android:name="com.onegravity.contactpicker.core.ContactPickerActivity"
            android:enabled="true"
            android:exported="false" >
            <intent-filter>
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
        </activity>

    </application>

</manifest>

3 :- My MainActivity.java
package com.example.the_king.findnotification;

import android.Manifest;
import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Path;
import android.os.Build;
import android.provider.ContactsContract;
import android.support.annotation.NonNull;
import android.support.v4.app.ActivityCompat;
import android.support.v4.content.ContextCompat;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.Toast;

import com.onegravity.contactpicker.contact.Contact;
import com.onegravity.contactpicker.contact.ContactDescription;
import com.onegravity.contactpicker.contact.ContactSortOrder;
import com.onegravity.contactpicker.core.ContactPickerActivity;
import com.onegravity.contactpicker.group.Group;
import com.onegravity.contactpicker.picture.ContactPictureType;

import java.util.List;

import static com.example.the_king.findnotification.R.style.ContactPicker_Theme_Light;

public class MainActivity extends AppCompatActivity {
    private Button mybtn;
    public boolean mDarkTheme;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
       
        mybtn = (Button)findViewById(R.id.mybtn);
        mybtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                OpenContact();
            }
        });
    }

    public void OpenContact(){
        boolean res = askPermission(0);
        if(res==true){
            startIntent();
        }
    }
    public void startIntent(){
        Intent intent = new Intent(this, ContactPickerActivity.class).putExtra(ContactPickerActivity.EXTRA_THEME,ContactPicker_Theme_Light).putExtra(ContactPickerActivity.EXTRA_CONTACT_BADGE_TYPE, ContactPictureType.ROUND.name()).putExtra(ContactPickerActivity.EXTRA_CONTACT_DESCRIPTION, ContactDescription.ADDRESS.name()).putExtra(ContactPickerActivity.EXTRA_SHOW_CHECK_ALL, true).putExtra(ContactPickerActivity.EXTRA_SELECT_CONTACTS_LIMIT, 0).putExtra(ContactPickerActivity.EXTRA_ONLY_CONTACTS_WITH_PHONE, false).putExtra(ContactPickerActivity.EXTRA_CONTACT_DESCRIPTION_TYPE, ContactsContract.CommonDataKinds.Email.TYPE_WORK).putExtra(ContactPickerActivity.EXTRA_CONTACT_SORT_ORDER, ContactSortOrder.AUTOMATIC.name());
        startActivityForResult(intent, 0);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == 0 && resultCode == Activity.RESULT_OK &&
                data != null && data.hasExtra(ContactPickerActivity.RESULT_CONTACT_DATA)) {

            // we got a result from the contact picker

            // process contacts
            List<Contact> contacts = (List<Contact>) data.getSerializableExtra(ContactPickerActivity.RESULT_CONTACT_DATA);
            for (Contact contact : contacts) {
                // process the contacts...
            }

            // process groups
            List<Group> groups = (List<Group>) data.getSerializableExtra(ContactPickerActivity.RESULT_GROUP_DATA);
            for (Group group : groups) {
                // process the groups...
            }
        }
    }
    //asking permission from the user to access to contact
    public boolean askPermission(int identification){
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.M){
            if(ContextCompat.checkSelfPermission(this, Manifest.permission.READ_CONTACTS) != PackageManager.PERMISSION_GRANTED){
                ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.READ_CONTACTS},identification);
                return false;
            }
            else{
                return true;
            }
        }else{
            return true;
        }
    }

    //Accordng to the permission result back and perform what data is selected from the user
    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        switch (requestCode){
            case 0:
                if(grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED){

                }else{
                    Toast.makeText(this,"Go Directive wants to access permission..Please give to access permission by click on + -> allow",Toast.LENGTH_LONG).show();
                }
                break;
            case 1:
                if(grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED){

                }else{
                    Toast.makeText(this,"Go Directive wants to access permission..Please give to access permission by click on + -> allow",Toast.LENGTH_LONG).show();
                }
                break;
        }
    }

}

4 :- activity_main.xml

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.the_king.findnotification.MainActivity">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/mybtn"
        android:text="Contact"
        />

</LinearLayout>

Can you suggest me any solution which solve this problem?

**Comment by 1gravity** [comment]
Can you show your ContactPicker_Theme_Light definition?

**Comment by DhiralKaniya** [comment]
I am extending your ContactPicker_Theme_Light  as you mentioned in the README.md.

**Comment by DhiralKaniya** [comment]
Hello 1gravity,

I got solution. I update my AndroidManifest.xml file with following code which help me.

1 :- AndroidManifest.xml file
![2](https://cloud.githubusercontent.com/assets/21332852/26436086/920253da-4131-11e7-9c24-973c7bcc99fd.jpg)


with the help of [https://stackoverflow.com/questions/42947370/1gravity-contacts-picker-library-for-android](url)

**Comment by 1gravity** [comment]
That's not a solution, that's just a coverup for your erroneous style definition. You can't extend a theme with a theme that has the same name.
You're doing:
`<style name="ContactPicker_Theme_Light" parent="@style/ContactPicker_Theme_Light">`
when you should be doing something like this:
`<style name="MyOwn_ContactPicker_Theme_Light" parent="@style/ContactPicker_Theme_Light">`
or
`<style name="ContactPicker_Theme_Light.Child">`

Defining the theme in the manifest might work for the moment but who knows if it will when they change the build tools (which they do all the time).

**Comment by 1gravity** [comment]
The real issue was that the check happened before the theme was set in code. While your solution works, it doesn't fix the issue that you couldn't set the theme in code which is what you want if the app supports multiple themes (like dark and light theme). I fixed that with version 1.3.2.

**Comment by DhiralKaniya** [comment]
@1gravity :-  Thanks for last solution now its works from the code with multiple theme.
