### ISSUE TITLE
Read_contacts permission issue

### ISSUE THREAD

**Issue by nonozelmar** [1gravity/Android-ContactPicker#3]
Hi , i tried to implement your library into my project but I get this log : `E/ContactPickerActivity: Contact permission hasn't been granted to this app, terminating.: uid 10061 does not have android.permission.READ_CONTACTS.` even thought i added the line ` <uses-permission android:name="android.permission.CONTACTS" />` to my Android manifest file.

Thanx in advance for your help.

SDK used : 23
Build : skd_google_phoneX86_64-userdebug 6.0 MASTER 3038907 test-keys
Device : Samsung s5 simulator

**Comment by 1gravity** [comment]
On Android 6 and higher you need to request the contacts permission at run-time: https://developer.android.com/training/permissions/requesting.html. The demo app shows how this can be done.
