### ISSUE TITLE
photoUri is always null even if Contact has image.

### ISSUE THREAD

**Issue by abhijeet-gupta** [1gravity/Android-ContactPicker#4]
Hi,

I want to use your Contact Picker Library in my project. We need the details of the picked contact by the user with the photo path of the contact. But the library always returns null in photoUri for all contacts (with photo and without photo).

Please let me know how we can able to get the photos for the picked contact.

One more things, we only want to show the contacts (in the list) that have at least one phone number. How we can achieve this.

Thanks in advance.

**Comment by 1gravity** [comment]
This is due to the fact that a Uri isn't Serializable. I will add a custom serialization to the Contact once I find the time to do so. Stay tuned.

**Comment by 1gravity** [comment]
That works too ;-)

**Comment by 1gravity** [comment]
Fixed with c3353fbb921478ecfe789a3e225e7a7c650068d2
