### ISSUE TITLE
Is it possible to limit selectable contacts?

### ISSUE THREAD

**Issue by aswanth-bonthala** [1gravity/Android-ContactPicker#6]
Hi in my project i need to pickup only 5 contacts at a time?is it possible to do?Once we reach the limit then contact should not be selected, it should auto unchecked and alert should display?Please guide me.

**Comment by Nikhil-z** [comment]
Yeah i also have same question . How to limit selecting contacts ?

**Comment by 1gravity** [comment]
Check out the OnContactCheckedListener and especially it's implementations in the ContactPickerActivity. That's where you can limit the number of selected contacts and show a dialog if needed.

**Comment by lwhiteley** [comment]
is there an example on how to tap into the listener or will there be a limit option for the library itself?

**Comment by lwhiteley** [comment]
submitted a PR that potentially solves this issue, folks here can test and continue the discussion in PR #8 

Thanks
